services:
  checklist-api-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: checklist-api-service
    env_file:
      - .env
    environment:
      IN_DOCKER: "true"
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    volumes:
      - ./logs:/app/logs
    networks:
      - checklist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  checklist-network:
    external: true